### ISSUE TITLE
dynamic item generation from data

### ISSUE THREAD

**Issue by starikcetin** [Paraboly/pwc-filter#16]
Example data structure:

```
fooDetails: Array(3)
    0:
        key: "Severity"
        value: "Medium"
        type: "accident"
    1:
        key: "Affected lanes"
        value: "Right-hand side"
        type: "construction"
```

Ideally, we should be able to have items dynamically generated on "key" property and filled with "value" property.

This essentially means adding and removing items to and from the config as the data changes.
